linux-system-roles/cockpit

.travis/runcollection.sh
.travis/utils.sh
tox.ini

- Adding .travis/runcollection.sh.
- Enabling collection as part of tox/travis tests.

RHELPLAN-56578 - sync collections related changes from template to cockpit role

---

README.md
defaults/main.yml
handlers/main.yml
tasks/main.yml
templates/cockpit.conf.j2

Add support for the role to optionally configure the cockpit.conf configuration file.  This config file controls several aspects of Cockpit (see "man cockpit.conf").

Support for Cockpit config file

---

templates/cockpit.conf.j2

BZ#2006230, BZ#2006231, BZ#2006233

Use {{ ansible_managed | comment }} to fix multi-line ansible_managed

---

CHANGELOG.md

[1.4.1] - 2022-11-15
--------------------
- none
- make role work with ansible-core 2.14 - fix ansible-lint 6.x issues (#81)
- none

Version 1.4.1 - CHANGELOG.md [citest skip]

---

CHANGELOG.md

[1.4.3] - 2023-01-20
--------------------
- none
- ansible-lint 6.x fixes
- Add check for non-inclusive language
- cleanup non-inclusive words.

Version 1.4.3 - CHANGELOG.md [citest skip]

---

CHANGELOG.md

[1.4.4] - 2023-04-06
--------------------
- Add README-ansible.md to refer Ansible intro page on linux-system-roles.github.io (#101)
- Fingerprint RHEL System Role managed config files (#102)

Version 1.4.4 - CHANGELOG.md [citest skip]

---

CHANGELOG.md

Create changelog update and release for version 1.4.7

docs(changelog): version 1.4.7 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.4.8
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

docs(changelog): version 1.4.8 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.2

docs(changelog): version 1.5.2 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.4

docs(changelog): version 1.5.4 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.5

docs(changelog): version 1.5.5 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.6
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

docs(changelog): version 1.5.6 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.7

docs(changelog): version 1.5.7 [citest skip]

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.5.8

docs(changelog): version 1.5.8 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.10

docs(changelog): version 1.5.10 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.11

docs(changelog): version 1.5.11 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.12

docs(changelog): version 1.5.12 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.13

docs(changelog): version 1.5.13 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.15

docs(changelog): version 1.5.15 [citest skip]

---

CHANGELOG.md

Update changelog and .README.html for version 1.5.16

docs(changelog): version 1.5.16 [citest skip]

---

.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-test.yml
.github/workflows/qemu-kvm-integration-tests.yml

Let's test it here and in another role, and once it goes green, I'll submit it to .github.git. This will help me with #212 and friends.

ci: Update to tox-lsr 3.7.0
