linux-system-roles/cockpit

vars/CentOS-8.yml

Running on CentOS-8 fails with ` "message": "Could not find or access 'CentOS-8.yml`
Added  `vars/CentOS-8.yml`  based off the existing RedHat one.

Add support for Centos-8

---

README.md
vars/CentOS-7.yml
vars/CentOS-8.yml
vars/Debian.yml
vars/Fedora.yml
vars/RedHat-7.yml
vars/RedHat-8.yml
vars/default.yml

The absolute minimum to give you a working Cockpit is
cockpit-{system,ws}. All distros provide an empty "cockpit" meta-package
that pulls in these, plus recommends a bunch of standard packages like
cockpit-packagekit. But don't rely on recommends to keep the role
robust.

Fix minimal vs. default packages

---

vars/Debian.yml

Current Debian 11 stable has Cockpit 239, which also does not build
cockpit-dashboard any more.

Drop cockpit-dashboard from Debian's "full" list

---

tests/tests_certificate.yml
tests/tests_certificate_runafter.yml

Change tests_certificate.yml to a cleaner approach which directly asks
certmonger to put the certificate into /etc/cockpit/ws-certs.d/, and
avoid the `runafter` script.  This approach relies on cockpit ≥ 211 and
https://github.com/linux-system-roles/certificate/pull/97,
so it does not work on RHEL/CentOS 7. Skip it with older cockpit
versions.
Move the previous test to tests_certificate_runafter.yml, to cover the
`runafter` script approach which works everywhere.
----
This is a step towards #37 which avoids the most annoying hack.
After this is in, I'll add these approaches to the documentation.

Test certmonger-generated certificates directly in cockpit/ws-certs.d/

---

tests/tests_certificate.yml

`ca: self-sign` is only broken on RHEL/CentOS 7, but works everywhere
else. So let's use it in tests_certificate.yml to cover this case as
well, and make sure it does not break again.
tests_certificate_runafter.yml still needs to keep `ca: local` and the
additional CA retrieval step, but it doesn't hurt to cover that mode.
-------
This exposes a set of problems and is still blocked, but filing an early draft to get CI feedback.
- Add documentation: PR #43

tests: Generate self-signed certificate for RHEL >= 8

---

README.md

Now that we have the necessary fixes and tests for integrating with lsr-certificates, let's document how to use that. I did not document the rather hairy `run_after:` [approach that's needed on RHEL 7](https://github.com/linux-system-roles/cockpit/blob/master/tests/tests_certificate_runafter.yml), and instead just added a note that this only works on RHEL ≥ 8.
I welcome any suggestions here, in particular for cleaning up my broken English. :wink: 
Rendered README is here: https://github.com/martinpitt/lsr-cockpit/tree/certs-doc#readme

Document how to generate a web server certificate, various small documentation improvements

---

tests/tests_certificate.yml
tests/tests_certificate_runafter.yml
tests/tests_config.yml
tests/tests_default.yml

Wrap tests into block:/always: so that the cleanup steps happen on
failed tests as well.
----
@richm : As discussed in your meeting last week. My previous PR #46 already uses that approach, this PR retrofits it for the existing tests.

tests: Run cleanup on failures as well

---

README.md
tasks/main.yml
tests/tasks/cleanup.yml
tests/tests_certificate_existing.yml

Add `cockpit_{certificate,key}:` role options which create
/etc/cockpit/ws-certs.d/50-system-role.{crt,key} symlinks to an existing
certificate.
This works only with cockpit >= 257, so conditionalize the test
accordingly.
Teach the generic test cleanup to remove all existing cockpit
certificates.
----
README preview: https://github.com/martinpitt/lsr-cockpit/tree/existing-cert#readme
This requires the certificate permission change in [Cockpit 257](https://cockpit-project.org/blog/cockpit-257.html). As of Nov 15, this only works in Fedora 35. The [Fedora 34 update](https://bodhi.fedoraproject.org/updates/FEDORA-2021-9b41f0e6c8) is still in updates-testing, and the RHEL 9.0 final nightly has not been re-composed yet to pick up 257 (which is through gating and in erratum since last Friday).

Add option to use an existing certificate

---

tests/tasks/cleanup.yml
tests/tests_packages_full.yml

This has bug reports such as [1], ensure that this generally works
everywhere.
[1] https://github.com/linux-system-roles/cockpit/issues/51
----
This works fine for me locally on RHEL 8.6 and Fedora 35, let's check on the other's. But #51 was reported against RHEL 8.5, so apparently something more special happens on Terry's machine.

Test "cockpit_packages: full" scenario

---

.gitignore
tasks/main.yml
tasks/set_vars.yml
tests/setup-snapshot.yml
tests/tests_certificate_runafter.yml
tests/tests_default.yml
vars/main.yml

Some users use `gather_facts: false` in their playbooks.  This changes
the role to work in that case, by gathering only the facts it requires
to run.
CI testing can be sped up by creating a snapshot image pre-installed
with packages.  tests/setup-snapshot.yml can be used by a CI system
to do this.

support gather_facts: false; support setup-snapshot.yml

---

.github/workflows/integration-tests.yml
README.md
handlers/main.yml
tasks/main.yml
tests/tasks/cleanup.yml
tests/tests_default.yml
tests/tests_port.yml

Introduce a `cockpit_port` variable which changes the default port 9090,
as per https://cockpit-project.org/guide/latest/listen.html#listen-systemd
This requires an extra step with SELinux: It only allows cockpit to own port
9090, so for any other port the user needs to adjust the policy first. As this
is outside of what the cockpit role ought to mess with, only document it and do
that in the tests.
Fixes #63 
------
Documentation preview: https://github.com/martinpitt/lsr-cockpit/tree/custom-port

Add customization of port

---

tests/tests_port.yml

libselinux-python3 does not exist in Debian/Ubuntu, so only install it
in Fedora/RedHat based distributions.
Drop the duplicated rule.
---
Fixes [this regression](https://github.com/linux-system-roles/cockpit/runs/7601244368?check_suite_focus=true#step:4:909) of the integration test.

tests: Don't install selinux-python on Debian/Ubuntu

---

.github/workflows/integration-tests.yml

The current LTS 22.04 is the more interesting target. This detects bugs
like [1]. Keep 20.04 running as well for the time being.
[1] https://github.com/linux-system-roles/certificate/pull/130
----
- Requires https://github.com/linux-system-roles/certificate/pull/130 to land first

[citest skip] workflows: Add integration-tests for Ubuntu 22.04

---

tests/tasks/clone_cert_role.yml
tests/tests_certificate.yml
tests/tests_certificate_runafter.yml

Following the comment https://github.com/linux-system-roles/cockpit/pull/76#issuecomment-1262432694 by @richm , clone the certificate role in the temporary dir.
Note: this is needed to make the CI tests pass.

Clone the certificate role in the temporary dir.

---

README.md
defaults/main.yml
meta/collection-requirements.yml
tasks/firewall.yml
tasks/main.yml
tasks/selinux.yml
tests/tasks/check_port.yml
tests/tasks/install_selinux_tools.yml
tests/tests_config.yml
tests/tests_packages_full.yml
tests/tests_port.yml
tests/tests_port2.yml

- Introduce cockpit_manage_firewall to use the firewall role to manage the cockpit service. Default to false - means the firewall role is not used.
- Introduce cockpit_manage_selinux to use the selinux role to manage the ports in the cockpit service. Assign websm_port_t to the cockpit service ports. Default to false - means the selinux role is not used.
- Add the test check task tasks/check_firewall_selinux.yml for verify the ports status.
- Add meta/collection-requirements.yml.

Use the firewall role and the selinux role from the cockpit role

---

CHANGELOG.md

[1.4.2] - 2022-11-21
--------------------
- none
- ansible-core 2.14 support - remove another warn
- use fedora.linux_system_roles.certificate role in tests
The dependencies will be installed everywhere, so just use them
in the tests

Version 1.4.2 - CHANGELOG.md [citest skip]

---

templates/cockpit.conf.j2
tests/tests_config.yml

Add role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.

Fingerprint RHEL System Role managed config files

---

tasks/main.yml
tests/tasks/check_port.yml

```
tasks/main.yml:17: no-changed-when: Commands should not change things if nothing needs doing.
```
Use `changed_when: true` so that the command will report changed if the
`when` condition is true and the command is executed.
```
tests/tasks/check_port.yml:34: risky-shell-pipe: Shells that use pipes should set the pipefail option.
```
add `pipefail` option.

additional ansible-lint fixes

---

README.md

For roles that use other system roles, they have a
`meta/collection-requirements.yml` file, and the README lists
these requirements and instructions.  However, these are only
required for github and Galaxy users, and not for users who
use the packaged roles, where it is confusing to see instructions
about installing requirements when none are needed.  We need to
make it easier to remove these sections when packaging.
Clean up some markdownlint and ansible-lint issues.

docs: clean up collection requirements section

---

README.md

Enhancement: Use FQCN for scenarios that use other linux system roles
Reason: Our RPM spec expects FQCN for included system roles.

docs: Use FQCN for scenarios that use other linux system roles

---

.ansible-lint
.ostree/get_ostree_data.sh
.ostree/packages-runtime-CentOS-9.txt
meta/collection-requirements.yml
tasks/main.yml
tasks/set_vars.yml
tests/tasks/cleanup.yml
tests/tasks/install_selinux_tools.yml
tests/tests_config.yml

The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …

refactor: improve support for ostree systems

---

tasks/main.yml
tests/tests_certificate_external.yml
tests/tests_certificate_runafter.yml
tests/tests_config.yml
tests/tests_default.yml
tests/tests_port.yml
tests/tests_port2.yml

Enhancement: Fix implicit octal values in main.yml
Reason: Forbidden implicit octal values "0644" were found on lines 50, 81, and additional occurrences.
Result: Updated to use explicit octal format for better readability and to adhere to linting standards.
Issue Tracker Tickets (Jira or BZ if any):na

ci: Fix implicit octal values

---

.markdownlint.yaml

Add `---` doc start to .markdownlint.yaml

ci: Use supported ansible-lint action; run ansible-lint against the collection

---

meta/collection-requirements.yml
tasks/setup-zypper.yml
vars/ALP-Dolomite.yml

Enhancement: This pull request adds the `ALP-Dolomite.yml` variable file and setup-zypper.yml to support SUSE ALP-Dolomite configurations.
Reason: The existing configuration does not cover [SUSE ALP](https://documentation.suse.com/alp/dolomite/html/alp-dolomite/index.html).
Result: Works as expected in the added operating system.
Issue Tracker Tickets (Jira or BZ if any):na

ci: Add ALP-Dolomite var file

---

tasks/setup-zypper.yml

Enhancement: Add check for Cockpit package installation status in reboot condition
Reason: To prevent unnecessary reboots by adding a check for changes in Cockpit package installations. 
Result: System reboots will now only occur if there's a change in Cockpit package installation status
Issue Tracker Tickets (Jira or BZ if any): na

ci: Add check for Cockpit package installation status in reboot condition

---

tasks/setup-zypper.yml

Enhancement: Redundant reboot task.
Reason: Removing unnecessary reboot task
Result: System will not reboot after package install
Issue Tracker Tickets (Jira or BZ if any):na

ci: Remove redundant task

---

tests/tests_config.yml

Enhancement: Gather python_version is tests_config.yml to gather ansible_python_version fact
Reason: The role didn't gather ansible_python_version but used it in tests_fcontext.yml, hence this test failed on Ansible-2.14 on RHEL 8.10
Result: The bug is fixed

test: Add python_version to test facts gather ansible_python_version

---

tests/tasks/cleanup.yml
tests/tests_certificate_existing.yml
tests/tests_certificate_external.yml
tests/tests_certificate_internal.yml
tests/tests_certificate_runafter.yml
tests/tests_port.yml

non-ostree system cleanup will remove the packages, which has
side effects such as stopping and removing services.  Cannot remove
packages on ostree system, so try to do something similar.

test: Ensure cleanup and proper service state on ostree

---

tasks/setup-dnf.yml
tests/tests_packages_full.yml

Cause: The dnf module is not installing cockpit-*
Consequence: The full list of requested packages is not installed.
Fix: Call the dnf command directly with the wildcard package name
and the packages to exclude.
Result: The requested wildcard packages are installed.

fix: wildcard package installation not working with dnf module

---

.ostree/packages-runtime-CentOS-10.txt
.ostree/packages-runtime-RedHat-10.txt
.ostree/packages-testing-RedHat-10.txt
meta/main.yml
vars/CentOS-10.yml
vars/RedHat-10.yml

According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …

fix: add support for EL10

---

README.md
defaults/main.yml
tasks/firewall.yml
tasks/selinux.yml
tasks/set_vars.yml
tasks/setup-zypper.yml
vars/SL-Micro.yml

Enhancement: - Added a block to identify and handle reboots for transactional update systems on package changes. Update README. Rename ALP-Dolomite var file to SL-Micro as the name is no longer used.
Reason: Ensure necessary reboots are managed, as changes on transactional update systems are applied in a separate snapshot and require a reboot to take effect.
Result: Manages system reboots for transactional update systems when a package is installed.
Issue Tracker Tickets (Jira or BZ if any):na

ci: Handle reboot for transactional update systems

---

tests/tests_packages_full.yml

Skip the check for missing excluded packages on ostree.  The packages
are built-in to the image - no easy way to build image with these
packages excluded.

test: skip check for excluded packages on ostree

---

tests/tests_packages_full.yml

The tests_packages_full test is failing on el9.6 and later - cockpit-pcp
is missing - use cockpit-machines instead which seems to be available
on all platforms.

test: cockpit-pcp is deprecated - use cockpit-machines

---

tests/tests_packages_full.yml

Ensure the correct package is looked for in the extra/full packages test.

test: full test uses cockpit-composer or cockpit-machines

---

README.md
tests/tasks/get_cockpit_group.yml

Cockpit 330 (RHEL 9.6/10.0/Fedora 40) does not have any static system groups any more, everything is handled through `DynamicUser=`.
The ownership of the certificate hasn't mattered since Cockpit 257 [1], which is in RHEL 8.7, 9.0, and all current Fedora/Debian/Ubuntu OSes.
Setting a certificate group *can* be useful to share it with other services (like symlinking a global LetsEncrypt cert to ws-certs.d/), but this isn't what our documentation and tests do -- they produce a certificate exclusively for Cockpit. 
Adjust the documentation and get_cockpit_group.yml to special-case the "cockpit-ws" group ownership for RHEL 7, similar to what other tests already do. Note that there was *never* any situation where the certificate needs to be owned by `cockpit-wsinstance` -- this was always …

test: Drop cockpit-ws* groups

---

.README.html
CHANGELOG.md

Update changelog and .README.html for version 1.5.14

docs(changelog): version 1.5.14 [citest skip]

---

.gitignore
tests/tasks/cleanup.yml

The "reverse dependencies will be removed along" assumption isn't true any more in Fedora ≥ 41, and it's also not explicitly documented [1]. Trying to remove cockpit-bridge now fails because the installed cockpit-system depends on it.
Use a glob to remove all cockpit packages instead.
[1] https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html
----
No release note, this is test only.
Fixes the [Fedora 41 failure](https://dl.fedoraproject.org/pub/alt/linuxsystemroles/logs/tf_cockpit-129_Fedora-41-2.17_20250329-123139/artifacts/) in #129 (periodic testing), and also Fedora 42 (see #200).

test: Remove all cockpit packages in cleanup

---

vars/RedHat-9.yml

Cause: Installing all "cockpit-*" packages with dnf does not work on at least CentOS 9: that publishes multiple versions of cockpit, in particular an old one where cockpit-pcp was still a separate package. Since version 326 [1] it was merged into cockpit-bridge.
Consequence: Playbook fails on package conflicts when configured with
`cockpit_packages: full` on CentOS 9.
Fix: Ignore the cockpit-pcp package on RHEL 9.
Result: `cockpit_packages: full` works again in all cases.
[1] https://github.com/cockpit-project/cockpit/releases/tag/326
----
This fixes the [test_packages_full failure](https://dl.fedoraproject.org/pub/alt/linuxsystemroles/logs/tf_cockpit-129_CentOS-Stream-9-2.17_20250329-123141/artifacts/tests_packages_full-ANSIBLE-2.17-test_playbooks_parallel-FAIL.log) which has plagued the …

fix: Ignore cockpit-pcp on RedHat 9

---

tasks/setup-dnf5.yml

`ansible_pkg_mgr` is `dnf5` on Fedora 42.
----
This was some side-issue which I originally needed for #203. That is obsolete now, but and this change currently doesn't have an observable effect -- but it's still a trap in the future, so let's fix it.

fix: Run Fedora 42 with dnf instead of default setup

---

tasks/setup-dnf.yml
vars/RedHat-9.yml

Commit 61ff76416c37036de67 statically ignored cockpit-pcp. But that changes the role behaviour on earlier RHEL 9.y versions with Cockpit < 326.
So revert the original change, and instead determine whether to ignore cockpit-pcp dynamically, by doing a version comparison on the available cockpit-bridge version.
----
Follow-up for https://github.com/linux-system-roles/cockpit/pull/204#discussion_r2028890046 . This still works on CentOS 9 (covered by integration tests). I also ran this against the "rhel-9-4" image (from internal config) and it behaves as expected, i.e. installs pcp:
```
TASK [linux-system-roles.cockpit : Get cockpit-bridge available version in "full" package install mode] ********************************
task path: /var/home/martin/upstream/lsr/cockpit/tests/roles/linux-system …
```

fix: Dynamically ignore cockpit-pcp

---

.github/workflows/integration-tests.yml

The "ubuntu-20.04" runner will be switched off in a week, and is currently browning out.
See https://github.com/actions/runner-images/issues/11101.
---
See the annotation in e.g. https://github.com/linux-system-roles/tox-lsr/actions/runs/14334537098/job/40179317006?pr=181

ci: Remove EOL ubuntu-20.04 runner, add 24.04

---

tasks/setup-dnf.yml

Cause: In some RHEL environments, dnf operations write some extra output like "This system is not registered with an entitlement server."
Consequence: This breaks the `dnf repoquery` parsing introduced in commit d64b5603037f and makes the role fail due to the invalid value comparison.
Fix: Only consider the last line (which will be the actual version number).
---
This does not trigger in our current test environments as they don't have sub-man etc. installed. But it [did fail](https://github.com/linux-system-roles/cockpit/actions/runs/14637916143/job/41073261651#step:12:909) during bootc container test in #212. This is quite an urgent regression fix, so let's land it separately:
> TASK [linux-system-roles.cockpit : Get cockpit-bridge available version in "full" package install mode] ***
> …

fix: Ignore extra lines in dnf repoquery parsing

---

.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-test.yml
.github/workflows/qemu-kvm-integration-tests.yml
handlers/main.yml
meta/main.yml
tasks/main.yml
tasks/set_vars.yml
tests/tasks/cleanup.yml
tests/tests_certificate_existing.yml
tests/tests_certificate_external.yml
tests/tests_certificate_internal.yml
tests/tests_certificate_runafter.yml
tests/tests_config.yml
tests/tests_default.yml
tests/tests_packages_full.yml
tests/tests_port.yml
tests/tests_port2.yml

Feature: Support running the cockpit role during container builds.
Reason: This is particularly useful for building bootc derivative OSes.
Result: These flags enable running the bootc container scenarios in CI, which ensures that the role works in buildah build environment. This allows us to officially support this role for image mode builds.
Do *not* enable the role for system containers (the `container`) flag. That currently fails due to SELinux not working properly there, and needs to be looked at separately if desired.
https://issues.redhat.com/browse/RHEL-88423
Skip the certmonger tests for non-booted environments, as certmonger requires a running system by design (these are a case for running the role in a deployed system). Also skip the firewall managed related checks for the time …

feat: Support this role in container builds
